version: '3'

services:

    backend:
        command: npm run serve

    frontend:
        command: npm run build

    nginx:
        container_name: nginx
        image: nginx
        restart: always
        volumes:
            - ./config/nginx:/etc/nginx/conf.d/
            - ./volumes/static:/static/

        ports:
            - "8080:8080"

        depends_on:
            - backend

        links:
            - backend:backend
