version: '3'

services:

    backend:

        container_name: backend
        build: ./containers/backend/
        command: npm run develop

        read_only: true
        volumes:
            - ./volumes/data/:/data
            - ./containers/backend:/backend/
            - /backend/node_modules

        expose:
            - 8000

    frontend:

        container_name: frontend
        build: ./containers/frontend
        command: npm run develop

        expose:
            - 3000

    nginx:

        container_name: nginx
        image: nginx
        restart: always
        volumes:
            - ./config/nginx_dev:/etc/nginx/conf.d/

        ports:
            - "8080:8080"

        depends_on:
            - backend
            - frontend

        links:
            - backend:backend
            - frontend:frontend
